spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123123
    url: jdbc:mysql://203.195.139.64/db_homework?characterEncoding=utf-8&useSSL=false
#    url: jdbc:mysql://www.liukang666.cn/db_homework?characterEncoding=utf-8&useSSL=false
    hikari:
      read-only: false
      connection-timeout: 60000
      idle-timeout: 60000
      validation-timeout: 3000
      max-lifetime: 60000
      login-timeout: 5
      maximum-pool-size: 60
      minimum-idle: 10
  jpa:
    show-sql: true
  resources:
    static-locations: file:${upload.savePath},file:${upload.tempPath}
  redis:
      host: www.liukang666.cn
      port: 6379
      password: lk15131112...redis_A
      timeout: 5000
      jedis:
        pool:
          max-idle: 8
          min-idle: 0

wechat:
  appId: wxaa5ec51c6c3a5d36
  secret: 6211d13c9dd84207fbfa7a9be392391a

template:
  #作业通知模板
  homeworkNotice: Tqn7f1XYXjAm7mBp2dm90vH5drcbsDImsTHac-AMZgQ
  homeworkPath: /homework
  #注册成功模板
  registerNotice: 6iYnad2ZsRwANpFYeUO_onnWb8vHKFPZduRAo9acRjE
  registerPath: /info