spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: zsr0925Xx
    url: jdbc:mysql://39.96.212.107/homework?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2b8
    hikari:
      read-only: false
      connection-timeout: 60000
      idle-timeout: 60000
      validation-timeout: 3000
      max-lifetime: 60000
      login-timeout: 5
      maximum-pool-size: 60
      minimum-idle: 10
  jpa:
    show-sql: true
  resources:
    static-locations: file:${upload.savePath},file:${upload.tempPath}
  redis:
    host:  39.96.212.107
    port: 6379
    password: zsr0925Xx
    timeout: 5000ms
    jedis:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1ms

wechat:
  appId: wxaa5ec51c6c3a5d36
  secret: 6211d13c9dd84207fbfa7a9be392391a

template:
  #作业通知模板
  homeworkNotice: bt6CSxvfPOqW_HkMJV2trZOuclxWpsw4JKJcHP4MGfQ
  homeworkPath: /pages/workDetail/main
  #注册成功模板
  registerNotice: 6iYnad2ZsRwANpFYeUO_onnWb8vHKFPZduRAo9acRjE
  registerPath: /pages/index/main