spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123123
    url: jdbc:mysql://www.liukang666.cn/db_homework?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true

wechat:
  appId: wx07c2f70bc511f031
  secret: 66c79c9d56271af7c71886812df0d306